//Generated by 24HRS
package Model;


public class Dlp{

	private int dlp_id;
	private int policy_id;
	private String words;

public Dlp(){
}

public Dlp(int dlp_id){
	this.dlp_id = dlp_id;
}
public Dlp(int dlp_id,int policy_id,String words){
	this.dlp_id = dlp_id;
	this.policy_id = policy_id;
	this.words = words;
}

public int getDlp_id(){
return dlp_id;
}

public void setDlp_id(int dlp_id){
	this.dlp_id = dlp_id;
}

public int getPolicy_id(){
return policy_id;
}

public void setPolicy_id(int policy_id){
	this.policy_id = policy_id;
}

public String getWords(){
return words;
}

public void setWords(String words){
	this.words = words;
}

}