//Generated by 24HRS
package Model;


public class Dlp_policy{

	private int dlp_policy_id;
	private String policy;
	private String description;

public Dlp_policy(){
}

public Dlp_policy(int dlp_policy_id){
	this.dlp_policy_id = dlp_policy_id;
}
public Dlp_policy(int dlp_policy_id,String policy,String description){
	this.dlp_policy_id = dlp_policy_id;
	this.policy = policy;
	this.description = description;
}

public int getDlp_policy_id(){
return dlp_policy_id;
}

public void setDlp_policy_id(int dlp_policy_id){
	this.dlp_policy_id = dlp_policy_id;
}

public String getPolicy(){
return policy;
}

public void setPolicy(String policy){
	this.policy = policy;
}

public String getDescription(){
return description;
}

public void setDescription(String description){
	this.description = description;
}

}