//Generated by 24HRS
package Model;

public class Msg {

    private int id;
    private String timestamp;
    private int sender_id;
    private int recever_id;
    private String content;

    public Msg() {
    }

    public Msg(int id) {
        this.id = id;
    }

    public Msg(int id, String timestamp, int sender_id, int recever_id, String content) {
        this.id = id;
        this.timestamp = timestamp;
        this.sender_id = sender_id;
        this.recever_id = recever_id;
        this.content = content;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public int getSender_id() {
        return sender_id;
    }

    public void setSender_id(int sender_id) {
        this.sender_id = sender_id;
    }

    public int getRecever_id() {
        return recever_id;
    }

    public void setRecever_id(int recever_id) {
        this.recever_id = recever_id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
