//Generated by 24HRS
package Model;

public class Msg {

    private int id;
    private String hash;
    private String previousHash;
    private String timeStamp;
    private int sender_id;
    private int recever_id;
    private String content;

    public Msg() {
    }

    public Msg(int id) {
        this.id = id;
    }

    public Msg(int id, String hash, String previousHash, String timeStamp, int sender_id, int recever_id, String content) {
        this.id = id;
        this.hash = hash;
        this.previousHash = previousHash;
        this.timeStamp = timeStamp;
        this.sender_id = sender_id;
        this.recever_id = recever_id;
        this.content = content;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getPreviousHash() {
        return previousHash;
    }

    public void setPreviousHash(String previousHash) {
        this.previousHash = previousHash;
    }

    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    public int getSender_id() {
        return sender_id;
    }

    public void setSender_id(int sender_id) {
        this.sender_id = sender_id;
    }

    public int getRecever_id() {
        return recever_id;
    }

    public void setRecever_id(int recever_id) {
        this.recever_id = recever_id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
