//Generated by 24HRS
package Model;


public class Smart_contract{

	private int smart_contract_id;
	private int policy_id;
	private String words;

public Smart_contract(){
}

public Smart_contract(int smart_contract_id){
	this.smart_contract_id = smart_contract_id;
}
public Smart_contract(int smart_contract_id,int policy_id,String words){
	this.smart_contract_id = smart_contract_id;
	this.policy_id = policy_id;
	this.words = words;
}

public int getSmart_contract_id(){
return smart_contract_id;
}

public void setSmart_contract_id(int smart_contract_id){
	this.smart_contract_id = smart_contract_id;
}

public int getPolicy_id(){
return policy_id;
}

public void setPolicy_id(int policy_id){
	this.policy_id = policy_id;
}

public String getWords(){
return words;
}

public void setWords(String words){
	this.words = words;
}

}