//Generated by 24HRS
package Model;


public class Smart_contract_policy{

	private int smart_contract_policy_id;
	private String policy;
	private String description;

public Smart_contract_policy(){
}

public Smart_contract_policy(int smart_contract_policy_id){
	this.smart_contract_policy_id = smart_contract_policy_id;
}
public Smart_contract_policy(int smart_contract_policy_id,String policy,String description){
	this.smart_contract_policy_id = smart_contract_policy_id;
	this.policy = policy;
	this.description = description;
}

public int getSmart_contract_policy_id(){
return smart_contract_policy_id;
}

public void setSmart_contract_policy_id(int smart_contract_policy_id){
	this.smart_contract_policy_id = smart_contract_policy_id;
}

public String getPolicy(){
return policy;
}

public void setPolicy(String policy){
	this.policy = policy;
}

public String getDescription(){
return description;
}

public void setDescription(String description){
	this.description = description;
}

}