//Generated by 24HRS
package Controller;

import Model.Dlp_policy;
import DataBaseConnector.Connector;
import Model.Dlp;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class Dlp_policyController {

    Connector con = Connector.getInstance();

    private Dlp_policyController() {
    }

    private static final Dlp_policyController obj = new Dlp_policyController();

    public static Dlp_policyController getInstance() {
        return obj;
    }

    public void Save(Dlp_policy data) throws Exception {
        con.getConnection();
        con.aud("INSERT INTO dlp_policy(policy,description) values ('" + data.getPolicy() + "','" + data.getDescription() + "') ");
    }

    public void Update(Dlp_policy data) throws Exception {
        con.getConnection();
        con.aud("UPDATE dlp_policy SET policy  = '" + data.getPolicy() + "',description  = '" + data.getDescription() + "' WHERE dlp_policy_id = '" + data.getDlp_policy_id() + "'");
    }

    public void Delete(Dlp_policy data) throws Exception {
        con.getConnection();
        con.aud("DELETE FROM dlp_policy WHERE dlp_policy_id = '" + data.getDlp_policy_id() + "'");
    }

    public List<Dlp_policy> SearchAll() throws Exception {
        List<Dlp_policy> objList = new ArrayList<Dlp_policy>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM dlp_policy");
        while (rset.next()) {
            Dlp_policy obj = new Dlp_policy();
            obj.setDlp_policy_id(rset.getInt(1));
            obj.setPolicy(rset.getString(2));
            obj.setDescription(rset.getString(3));
            objList.add(obj);
        }

        return objList;
    }

    public List<Dlp_policy> Search(Dlp_policy data) throws Exception {
        List<Dlp_policy> objList = new ArrayList<Dlp_policy>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM dlp_policy WHERE dlp_policy_id = '" + data.getDlp_policy_id() + "'");
        while (rset.next()) {
            Dlp_policy obj = new Dlp_policy();
            obj.setDlp_policy_id(rset.getInt(1));
            obj.setPolicy(rset.getString(2));
            obj.setDescription(rset.getString(3));
            objList.add(obj);
        }

        return objList;
    }

    public List<String> getKeywords() throws Exception {
        List<String> list = new ArrayList<>();
        List<Dlp_policy> objList = new ArrayList<Dlp_policy>();
        con.getConnection();

        ResultSet rset = con.srh("SELECT * FROM dlp_policy");
        while (rset.next()) {
            Dlp_policy obj = new Dlp_policy();
            obj.setDlp_policy_id(rset.getInt(1));
            obj.setPolicy(rset.getString(2));
            obj.setDescription(rset.getString(3));
            objList.add(obj);
        }

        for (int i = 0; i < objList.size(); i++) {
            String result = "";
            ResultSet rs = con.srh("SELECT * FROM dlp WHERE policy_id = '" + objList.get(i).getDlp_policy_id() + "'");
            while (rs.next()) {
                result = result + rs.getString(3) + ",";
            }
            list.add(result);
        }

        return list;
    }

}
