//Generated by 24HRS
package Controller;


import Model.Dlp;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class DlpController{

	Connector con = Connector.getInstance();

	private DlpController(){
	}

	private static final DlpController obj = new DlpController();

	public static DlpController getInstance(){
		return obj;
	}

	public void Save(Dlp data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO dlp(policy_id,words) values ('" + data.getPolicy_id()+ "','" + data.getWords()+ "') " );
	}

	public void Update(Dlp data) throws Exception {
		con.getConnection();
		con.aud("UPDATE dlp SET policy_id  = '" + data.getPolicy_id()+ "',words  = '" + data.getWords()+ "' WHERE dlp_id = '" + data.getDlp_id()+ "'");
	}

	public void Delete(Dlp data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM dlp WHERE dlp_id = '" + data.getDlp_id()+ "'");
	}

	public List<Dlp> SearchAll() throws Exception {
		List<Dlp> objList = new ArrayList<Dlp>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM dlp");
		while(rset.next()){
			Dlp obj = new Dlp();
			obj.setDlp_id(rset.getInt(1));
			obj.setPolicy_id(rset.getInt(2));
			obj.setWords(rset.getString(3));
			objList.add(obj);
		}

	return objList;
	}

	public List<Dlp> Search(Dlp data) throws Exception {
		List<Dlp> objList = new ArrayList<Dlp>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM dlp WHERE dlp_id = '" + data.getDlp_id()+ "'");
		while(rset.next()){
			Dlp obj = new Dlp();
			obj.setDlp_id(rset.getInt(1));
			obj.setPolicy_id(rset.getInt(2));
			obj.setWords(rset.getString(3));
			objList.add(obj);
		}

	return objList;
	}

}