//Generated by 24HRS
package Controller;

import Model.Msg;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

public class MsgController {

    Connector con = Connector.getInstance();

    private MsgController() {
    }

    private static final MsgController obj = new MsgController();

    public static MsgController getInstance() {
        return obj;
    }

    public void Save(Msg data) throws Exception {
        con.getConnection();
        con.aud("INSERT INTO msg(timestamp,sender_id,recever_id,content) values ('" + data.getTimestamp() + "','" + data.getSender_id() + "','" + data.getRecever_id() + "','" + data.getContent() + "') ");
    }

    public void Update(Msg data) throws Exception {
        con.getConnection();
        con.aud("UPDATE msg SET timestamp  = '" + data.getTimestamp() + "',sender_id  = '" + data.getSender_id() + "',recever_id  = '" + data.getRecever_id() + "',content  = '" + data.getContent() + "' WHERE id = '" + data.getId() + "'");
    }

    public void Delete(Msg data) throws Exception {
        con.getConnection();
        con.aud("DELETE FROM msg WHERE id = '" + data.getId() + "'");
    }

    public List<Msg> SearchAll() throws Exception {
        List<Msg> objList = new ArrayList<Msg>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM msg");
        while (rset.next()) {
            Msg obj = new Msg();
            obj.setId(rset.getInt(1));
            obj.setTimestamp(rset.getString(2));
            obj.setSender_id(rset.getInt(3));
            obj.setRecever_id(rset.getInt(4));
            obj.setContent(rset.getString(5));
            objList.add(obj);
        }

        return objList;
    }

    public List<Msg> Search(int id1, int id2) throws Exception {
        List<Msg> objList = new ArrayList<Msg>();
        con.getConnection();
        ResultSet rset = con.srh("SELECT * FROM msg WHERE sender_id = '" + id1 + "' AND recever_id = '" + id2 + "' OR sender_id = '" + id2 + "' AND recever_id = '" + id1 + "'");
        while (rset.next()) {
            Msg obj = new Msg();
            obj.setId(rset.getInt(1));
            obj.setTimestamp(rset.getString(2));
            obj.setSender_id(rset.getInt(3));
            obj.setRecever_id(rset.getInt(4));
            obj.setContent(rset.getString(5));
            objList.add(obj);
        }

        return objList;
    }

}
