//Generated by 24HRS
package Controller;


import Model.Smart_contract;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class Smart_contractController{

	Connector con = Connector.getInstance();

	private Smart_contractController(){
	}

	private static final Smart_contractController obj = new Smart_contractController();

	public static Smart_contractController getInstance(){
		return obj;
	}

	public void Save(Smart_contract data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO smart_contract(policy_id,words) values ('" + data.getPolicy_id()+ "','" + data.getWords()+ "') " );
	}

	public void Update(Smart_contract data) throws Exception {
		con.getConnection();
		con.aud("UPDATE smart_contract SET policy_id  = '" + data.getPolicy_id()+ "',words  = '" + data.getWords()+ "' WHERE smart_contract_id = '" + data.getSmart_contract_id()+ "'");
	}

	public void Delete(Smart_contract data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM smart_contract WHERE smart_contract_id = '" + data.getSmart_contract_id()+ "'");
	}

	public List<Smart_contract> SearchAll() throws Exception {
		List<Smart_contract> objList = new ArrayList<Smart_contract>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM smart_contract");
		while(rset.next()){
			Smart_contract obj = new Smart_contract();
			obj.setSmart_contract_id(rset.getInt(1));
			obj.setPolicy_id(rset.getInt(2));
			obj.setWords(rset.getString(3));
			objList.add(obj);
		}

	return objList;
	}

	public List<Smart_contract> Search(Smart_contract data) throws Exception {
		List<Smart_contract> objList = new ArrayList<Smart_contract>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM smart_contract WHERE smart_contract_id = '" + data.getSmart_contract_id()+ "'");
		while(rset.next()){
			Smart_contract obj = new Smart_contract();
			obj.setSmart_contract_id(rset.getInt(1));
			obj.setPolicy_id(rset.getInt(2));
			obj.setWords(rset.getString(3));
			objList.add(obj);
		}

	return objList;
	}

}