//Generated by 24HRS
package Controller;


import Model.Smart_contract_policy;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class Smart_contract_policyController{

	Connector con = Connector.getInstance();

	private Smart_contract_policyController(){
	}

	private static final Smart_contract_policyController obj = new Smart_contract_policyController();

	public static Smart_contract_policyController getInstance(){
		return obj;
	}

	public void Save(Smart_contract_policy data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO smart_contract_policy(policy,description) values ('" + data.getPolicy()+ "','" + data.getDescription()+ "') " );
	}

	public void Update(Smart_contract_policy data) throws Exception {
		con.getConnection();
		con.aud("UPDATE smart_contract_policy SET policy  = '" + data.getPolicy()+ "',description  = '" + data.getDescription()+ "' WHERE smart_contract_policy_id = '" + data.getSmart_contract_policy_id()+ "'");
	}

	public void Delete(Smart_contract_policy data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM smart_contract_policy WHERE smart_contract_policy_id = '" + data.getSmart_contract_policy_id()+ "'");
	}

	public List<Smart_contract_policy> SearchAll() throws Exception {
		List<Smart_contract_policy> objList = new ArrayList<Smart_contract_policy>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM smart_contract_policy");
		while(rset.next()){
			Smart_contract_policy obj = new Smart_contract_policy();
			obj.setSmart_contract_policy_id(rset.getInt(1));
			obj.setPolicy(rset.getString(2));
			obj.setDescription(rset.getString(3));
			objList.add(obj);
		}

	return objList;
	}

	public List<Smart_contract_policy> Search(Smart_contract_policy data) throws Exception {
		List<Smart_contract_policy> objList = new ArrayList<Smart_contract_policy>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM smart_contract_policy WHERE smart_contract_policy_id = '" + data.getSmart_contract_policy_id()+ "'");
		while(rset.next()){
			Smart_contract_policy obj = new Smart_contract_policy();
			obj.setSmart_contract_policy_id(rset.getInt(1));
			obj.setPolicy(rset.getString(2));
			obj.setDescription(rset.getString(3));
			objList.add(obj);
		}

	return objList;
	}

}