//Generated by 24HRS
package Controller;


import Model.User;
import DataBaseConnector.Connector;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;


public class UserController{

	Connector con = Connector.getInstance();

	private UserController(){
	}

	private static final UserController obj = new UserController();

	public static UserController getInstance(){
		return obj;
	}

	public void Save(User data) throws Exception {
		con.getConnection();
		con.aud("INSERT INTO user(user_fullname,usertype,email,username,password,public_key,private_key) values ('" + data.getUser_fullname()+ "','" + data.getUsertype()+ "','" + data.getEmail()+ "','" + data.getUsername()+ "','" + data.getPassword()+ "','" + data.getPublic_key()+ "','" + data.getPrivate_key()+ "') " );
	}

	public void Update(User data) throws Exception {
		con.getConnection();
		con.aud("UPDATE user SET user_fullname  = '" + data.getUser_fullname()+ "',usertype  = '" + data.getUsertype()+ "',email  = '" + data.getEmail()+ "',username  = '" + data.getUsername()+ "',password  = '" + data.getPassword()+ "',public_key  = '" + data.getPublic_key()+ "',private_key  = '" + data.getPrivate_key()+ "' WHERE user_id = '" + data.getUser_id()+ "'");
	}

	public void Delete(User data) throws Exception {
		con.getConnection();
		con.aud("DELETE FROM user WHERE user_id = '" + data.getUser_id()+ "'");
	}

	public List<User> SearchAll() throws Exception {
		List<User> objList = new ArrayList<User>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM user");
		while(rset.next()){
			User obj = new User();
			obj.setUser_id(rset.getInt(1));
			obj.setUser_fullname(rset.getString(2));
			obj.setUsertype(rset.getString(3));
			obj.setEmail(rset.getString(4));
			obj.setUsername(rset.getString(5));
			obj.setPassword(rset.getString(6));
			obj.setPublic_key(rset.getString(7));
			obj.setPrivate_key(rset.getString(8));
			objList.add(obj);
		}

	return objList;
	}

	public List<User> Search(User data) throws Exception {
		List<User> objList = new ArrayList<User>();
		con.getConnection();
		ResultSet rset = con.srh("SELECT * FROM user WHERE user_id = '" + data.getUser_id()+ "'");
		while(rset.next()){
			User obj = new User();
			obj.setUser_id(rset.getInt(1));
			obj.setUser_fullname(rset.getString(2));
			obj.setUsertype(rset.getString(3));
			obj.setEmail(rset.getString(4));
			obj.setUsername(rset.getString(5));
			obj.setPassword(rset.getString(6));
			obj.setPublic_key(rset.getString(7));
			obj.setPrivate_key(rset.getString(8));
			objList.add(obj);
		}

	return objList;
	}

}